-- MySQL Script generated by MySQL Workbench
-- Tue Apr 13 12:02:49 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


-- -----------------------------------------------------
-- Schema paymybuddy
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema paymybuddy
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS "paymybuddy";

-- -----------------------------------------------------
-- Table "paymybuddy"."users"
-- -----------------------------------------------------
CREATE TABLE "paymybuddy"."users"
(
    "id"         INT          NOT NULL,
    "first_name" VARCHAR(16)   NOT NULL,
    "last_name" VARCHAR(45)   NOT NULL,
    "email"     VARCHAR(255)  NOT NULL,
    "password"  VARCHAR(255)  NOT NULL,
    "birthdate" TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "balance"   DECIMAL(65,2) NOT NULL,
    PRIMARY KEY ("id")
);;


-- -----------------------------------------------------
-- Table "paymybuddy"."transactions"
-- -----------------------------------------------------
CREATE TABLE "paymybuddy"."transactions"
(
    "id"              BIGINT        NOT NULL,
    "date"            TIMESTAMP     NOT NULL,
    "amount"          DECIMAL(5, 2) NOT NULL,
    "wording"         TEXT          NULL,
    "type"            VARCHAR(45)   NOT NULL,
    "sender_id"       INT           NULL,
    "receiver_id"     INT           NOT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "sender_id"
        FOREIGN KEY ("sender_id")
            REFERENCES "paymybuddy"."users" ("id")
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT "receiver_id"
        FOREIGN KEY ("receiver_id")
            REFERENCES "paymybuddy"."users" ("id")
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
);;


-- -----------------------------------------------------
-- Table "paymybuddy"."friends"
-- -----------------------------------------------------
CREATE TABLE "paymybuddy"."friends"
(
    "id"             INT NOT NULL,
    "user_id"        INT NOT NULL,
    "friend_user_id" INT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "user_id"
        FOREIGN KEY ("user_id")
            REFERENCES "paymybuddy"."users" ("id")
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT "friend_user_id"
        FOREIGN KEY ("friend_user_id")
            REFERENCES "paymybuddy"."users" ("id")
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
);;


DROP SEQUENCE IF EXISTS "paymybuddy"."users_id_sequence";
CREATE SEQUENCE "paymybuddy"."users_id_sequence";
ALTER TABLE "paymybuddy"."users"
 ALTER COLUMN "id" SET DEFAULT NEXTVAL('"paymybuddy"."users_id_sequence"');


DROP SEQUENCE IF EXISTS "paymybuddy"."friends_id_sequence";
CREATE SEQUENCE "paymybuddy"."friends_id_sequence";
ALTER TABLE "paymybuddy"."friends"
    ALTER COLUMN "id" SET DEFAULT NEXTVAL('"paymybuddy"."friends_id_sequence"');

CREATE SEQUENCE hibernate_sequence START 1;
