-- MySQL Script generated by MySQL Workbench
-- Tue Apr 13 12:02:49 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


-- -----------------------------------------------------
-- Schema paymybuddy
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema paymybuddy
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS "paymybuddy";

-- -----------------------------------------------------
-- Table "paymybuddy"."users"
-- -----------------------------------------------------
CREATE TABLE "paymybuddy"."users"
(
    "id"         INT          NOT NULL,
    "first_name" VARCHAR(16)  NOT NULL,
    "last_name"  VARCHAR(45)  NOT NULL,
    "email"      VARCHAR(255) NOT NULL,
    "password"   VARCHAR(255) NOT NULL,
    "birthdate"  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id")
);;


-- -----------------------------------------------------
-- Table "paymybuddy"."internal_bank_account"
-- -----------------------------------------------------
CREATE TABLE "paymybuddy"."internal_bank_account"
(
    "id"      INT            NOT NULL,
    "balance" DECIMAL(65, 2) NOT NULL,
    "user_id" INT            NOT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "user_id"
        FOREIGN KEY ("user_id")
            REFERENCES "paymybuddy"."users" ("id")
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
);;

-- -----------------------------------------------------
-- Table "paymybuddy"."external_bank_account"
-- -----------------------------------------------------
CREATE TABLE "paymybuddy"."external_bank_account"
(
    "id"      INT            NOT NULL,
    "rib"     VARCHAR(27)    NOT NULL,
    "name"    VARCHAR(25)    NOT NULL,
    "user_id" INT            NOT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "user_id"
        FOREIGN KEY ("user_id")
            REFERENCES "paymybuddy"."users" ("id")
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
);;


-- -----------------------------------------------------
-- Table "paymybuddy"."transactions"
-- -----------------------------------------------------
CREATE TABLE "paymybuddy"."transactions"
(
    "id"              BIGINT        NOT NULL,
    "external_bank_account_id" INT           NOT NULL,
    "internal_bank_account_id" INT           NOT NULL,
    "date"            TIMESTAMP     NOT NULL,
    "amount"          DECIMAL(5, 2) NOT NULL,
    "wording"         TEXT          NULL,
    "type"            VARCHAR(45)   NOT NULL,
    "sender_id"       INT           NOT NULL,
    "receiver_id"     INT           NOT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "external_bank_account_id"
        FOREIGN KEY ("external_bank_account_id")
            REFERENCES "paymybuddy"."external_bank_account" ("id")
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT "internal_bank_account_id"
        FOREIGN KEY ("internal_bank_account_id")
            REFERENCES "paymybuddy"."internal_bank_account" ("id")
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT "sender_id"
        FOREIGN KEY ("sender_id")
            REFERENCES "paymybuddy"."users" ("id")
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT "receiver_id"
        FOREIGN KEY ("receiver_id")
            REFERENCES "paymybuddy"."users" ("id")
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
);;


-- -----------------------------------------------------
-- Table "paymybuddy"."friends"
-- -----------------------------------------------------
CREATE TABLE "paymybuddy"."friends"
(
    "id"             INT NOT NULL,
    "user_id"        INT NOT NULL,
    "friend_user_id" INT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "user_id"
        FOREIGN KEY ("user_id")
            REFERENCES "paymybuddy"."users" ("id")
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT "friend_user_id"
        FOREIGN KEY ("friend_user_id")
            REFERENCES "paymybuddy"."users" ("id")
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
);;

create table if not exists persistent_logins (
    username VARCHAR(255) not null,
    series varchar(64) primary key,
    token varchar(64) not null,
    last_used timestamp not null
    );


DROP SEQUENCE IF EXISTS "paymybuddy"."users_id_sequence";
CREATE SEQUENCE "paymybuddy"."users_id_sequence";
ALTER TABLE "paymybuddy"."users"
    ALTER COLUMN "id" SET DEFAULT NEXTVAL('"paymybuddy"."users_id_sequence"');
DROP SEQUENCE IF EXISTS "paymybuddy"."external_bank_account_id_sequence";
CREATE SEQUENCE "paymybuddy"."external_bank_account_id_sequence";
ALTER TABLE "paymybuddy"."external_bank_account"
    ALTER COLUMN "id" SET DEFAULT NEXTVAL('"paymybuddy"."external_bank_account_id_sequence"');

DROP SEQUENCE IF EXISTS "paymybuddy"."internal_bank_account_id_sequence";
CREATE SEQUENCE "paymybuddy"."internal_bank_account_id_sequence";
ALTER TABLE "paymybuddy"."internal_bank_account"
    ALTER COLUMN "id" SET DEFAULT NEXTVAL('"paymybuddy"."internal_bank_account_id_sequence"');

DROP SEQUENCE IF EXISTS "paymybuddy"."friends_id_sequence";
CREATE SEQUENCE "paymybuddy"."friends_id_sequence";
ALTER TABLE "paymybuddy"."friends"
    ALTER COLUMN "id" SET DEFAULT NEXTVAL('"paymybuddy"."friends_id_sequence"');

CREATE SEQUENCE hibernate_sequence START 1;
